Citizen.CreateThread(function()
	AddTextEntry("BCSDDET", "BCSD Yosemite")
	AddTextEntry("BCSDBUF", "BCSD Buffalo SX")
	AddTextEntry("BCSDSQ", "BCSD Squaddie")
	AddTextEntry("BCSDST", "BCSD Stanier")
	AddTextEntry("BCSDSCT", "BCSD Scout")
	AddTextEntry("BCSDSCT2", "BCSD Scout (Slicktop)")
	AddTextEntry("BCSDSWAT", "BCSD Riot")
	AddTextEntry("BCSDB", "BCSD Wintergreen")
	AddTextEntry("BCSDHELI", "BCSD Frogger")
	AddTextEntry("BCSDNAL", "BCSD Alamo")
end)